version: '3.8'

services:
  # JSON Oracle API Backend
  json-oracle-api:
    build: .
    ports:
      - "3000:3000"
    environment:
      - RUST_LOG=info
      - PORT=3000
      - OLLAMA_BASE_URL=http://ollama:11434
      - OLLAMA_MODEL=llama2
      - MAX_TIMEOUT_SECONDS=120
    depends_on:
      - ollama
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    networks:
      - json-oracle-network
    restart: unless-stopped

  # Ollama AI Service
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
    networks:
      - json-oracle-network
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  # Bolt UI Frontend
  bolt-ui:
    build:
      context: ./bolt_ui
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:3000/api
      - VITE_WS_URL=ws://localhost:3000/ws
      - NODE_ENV=development
    depends_on:
      - json-oracle-api
    volumes:
      - ./bolt_ui:/app
      - /app/node_modules
    networks:
      - json-oracle-network
    restart: unless-stopped

  # Nginx Reverse Proxy (Production)
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - json-oracle-api
      - bolt-ui
    networks:
      - json-oracle-network
    restart: unless-stopped
    profiles:
      - production

  # Redis for caching (Optional)
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - json-oracle-network
    restart: unless-stopped
    profiles:
      - production

  # PostgreSQL for data persistence (Optional)
  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=json_oracle
      - POSTGRES_USER=json_oracle
      - POSTGRES_PASSWORD=json_oracle_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - json-oracle-network
    restart: unless-stopped
    profiles:
      - production

volumes:
  ollama_data:
  redis_data:
  postgres_data:

networks:
  json-oracle-network:
    driver: bridge
