# fly.toml app configuration file generated for ai-json-analysis-api on 2024-01-15T10:00:00Z

app = 'ai-json-analysis-api'
primary_region = 'lax'

[build]

[env]
  RUST_LOG = 'info'
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512

[[vm]]
  cpu_kind = 'shared'
  cpus = 2
  memory_mb = 1024

[metrics]
  port = 9091
  path = '/metrics'
